name: trading-bot-env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10.10
  - pip
  - pandas
  - scikit-learn
  - tensorflow
  - gymnasium
  - ipykernel
  - matplotlib
  - numpy
  - tqdm
  - pip:
    - gym-trading-env
    - ta
    - azureml-mlflow